spring:
  profiles:
    active: test
  datasource:
    url: jdbc:mariadb://localhost:3306/mariadb
    username: root
    password: a1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
